In [22]:
import numpy as np
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori,association_rules

In [14]:
!pip install mlxtend

Requirement already satisfied: mlxtend in c:\users\amanp\anaconda3\lib\site-packages (0.23.0)
Requirement already satisfied: joblib>=0.13.2 in c:\users\amanp\anaconda3\lib\site-packages (from mlxtend) (1.1.1)
Requirement already satisfied: matplotlib>=3.0.0 in c:\users\amanp\anaconda3\lib\site-packages (from mlxtend) (3.7.0)
Requirement already satisfied: pandas>=0.24.2 in c:\users\amanp\anaconda3\lib\site-packages (from mlxtend) (1.5.3)
Requirement already satisfied: scikit-learn>=1.0.2 in c:\users\amanp\anaconda3\lib\site-packages (from mlxtend) (1.2.1)
Requirement already satisfied: scipy>=1.2.1 in c:\users\amanp\anaconda3\lib\site-packages (from mlxtend) (1.10.0)
Requirement already satisfied: numpy>=1.16.2 in c:\users\amanp\anaconda3\lib\site-packages (from mlxtend) (1.23.5)
Requirement already satisfied: pillow>=6.2.0 in c:\users\amanp\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (9.4.0)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\amanp\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (2.8.2)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\amanp\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (4.25.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\amanp\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (3.0.9)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\amanp\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (1.4.4)
Requirement already satisfied: cycler>=0.10 in c:\users\amanp\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (0.11.0)
Requirement already satisfied: packaging>=20.0 in c:\users\amanp\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (22.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\amanp\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (1.0.5)
Requirement already satisfied: pytz>=2020.1 in c:\users\amanp\anaconda3\lib\site-packages (from pandas>=0.24.2->mlxtend) (2022.7)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\amanp\anaconda3\lib\site-packages (from scikit-learn>=1.0.2->mlxtend) (2.2.0)
Requirement already satisfied: six>=1.5 in c:\users\amanp\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.0.0->mlxtend) (1.16.0)

In [4]:
import csv

In [5]:
data = []
with open("./Market_Basket_Optimisation.csv") as file:
    reader = csv.reader(file, delimiter=',')
    for row in reader:
        data +=[row]

In [6]:
data[1:10]

[['burgers', 'meatballs', 'eggs'],
 ['chutney'],
 ['turkey', 'avocado'],
 ['mineral water', 'milk', 'energy bar', 'whole wheat rice', 'green tea'],
 ['low fat yogurt'],
 ['whole wheat pasta', 'french fries'],
 ['soup', 'light cream', 'shallot'],
 ['frozen vegetables', 'spaghetti', 'green tea'],
 ['french fries']]

In [7]:
len(data)

7501

In [8]:
TE = TransactionEncoder()
x = TE.fit_transform(data)

In [9]:
x

array([[False,  True,  True, ...,  True, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False,  True, False]])

In [10]:
TE.columns_

[' asparagus',
 'almonds',
 'antioxydant juice',
 'asparagus',
 'avocado',
 'babies food',
 'bacon',
 'barbecue sauce',
 'black tea',
 'blueberries',
 'body spray',
 'bramble',
 'brownies',
 'bug spray',
 'burger sauce',
 'burgers',
 'butter',
 'cake',
 'candy bars',
 'carrots',
 'cauliflower',
 'cereals',
 'champagne',
 'chicken',
 'chili',
 'chocolate',
 'chocolate bread',
 'chutney',
 'cider',
 'clothes accessories',
 'cookies',
 'cooking oil',
 'corn',
 'cottage cheese',
 'cream',
 'dessert wine',
 'eggplant',
 'eggs',
 'energy bar',
 'energy drink',
 'escalope',
 'extra dark chocolate',
 'flax seed',
 'french fries',
 'french wine',
 'fresh bread',
 'fresh tuna',
 'fromage blanc',
 'frozen smoothie',
 'frozen vegetables',
 'gluten free bar',
 'grated cheese',
 'green beans',
 'green grapes',
 'green tea',
 'ground beef',
 'gums',
 'ham',
 'hand protein bar',
 'herb & pepper',
 'honey',
 'hot dogs',
 'ketchup',
 'light cream',
 'light mayo',
 'low fat yogurt',
 'magazines',
 'mashed potato',
 'mayonnaise',
 'meatballs',
 'melons',
 'milk',
 'mineral water',
 'mint',
 'mint green tea',
 'muffins',
 'mushroom cream sauce',
 'napkins',
 'nonfat milk',
 'oatmeal',
 'oil',
 'olive oil',
 'pancakes',
 'parmesan cheese',
 'pasta',
 'pepper',
 'pet food',
 'pickles',
 'protein bar',
 'red wine',
 'rice',
 'salad',
 'salmon',
 'salt',
 'sandwich',
 'shallot',
 'shampoo',
 'shrimp',
 'soda',
 'soup',
 'spaghetti',
 'sparkling water',
 'spinach',
 'strawberries',
 'strong cheese',
 'tea',
 'tomato juice',
 'tomato sauce',
 'tomatoes',
 'toothpaste',
 'turkey',
 'vegetables mix',
 'water spray',
 'white wine',
 'whole weat flour',
 'whole wheat pasta',
 'whole wheat rice',
 'yams',
 'yogurt cake',
 'zucchini']

In [11]:
df = pd.DataFrame(x,columns = TE.columns_)

In [12]:
df

,asparagus,almonds,antioxydant juice,asparagus,avocado,babies food,bacon,barbecue sauce,black tea,blueberries,...,turkey,vegetables mix,water spray,white wine,whole weat flour,whole wheat pasta,whole wheat rice,yams,yogurt cake,zucchini
0,False,True,True,False,True,False,False,False,False,False,...,False,True,False,False,True,False,False,True,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,True,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7496,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7497,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7498,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7499,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7500,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False

In [18]:
freq_of_itemset = apriori(df, min_support=0.003, use_colnames=True)

In [19]:
freq_of_itemset

       support                                           itemsets
0     0.020397                                          (almonds)
1     0.008932                                (antioxydant juice)
2     0.004666                                        (asparagus)
3     0.033329                                          (avocado)
4     0.004533                                      (babies food)
...        ...                                                ...
1438  0.003066  (mineral water, pancakes, ground beef, spaghetti)
1439  0.003066  (mineral water, spaghetti, ground beef, tomatoes)
1440  0.003333        (mineral water, spaghetti, milk, olive oil)
1441  0.003066           (mineral water, spaghetti, milk, shrimp)
1442  0.003333         (mineral water, spaghetti, milk, tomatoes)

[1443 rows x 2 columns]

In [23]:
rules = association_rules(freq_of_itemset,metric='lift',min_threshold=0.1)

In [24]:
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
0,(almonds),(burgers),0.020397,0.087188,0.005199,0.254902,2.923577,0.003421,1.225089,0.671653
1,(burgers),(almonds),0.087188,0.020397,0.005199,0.059633,2.923577,0.003421,1.041724,0.720799
2,(almonds),(cake),0.020397,0.081056,0.003066,0.150327,1.854607,0.001413,1.081527,0.470397
3,(cake),(almonds),0.081056,0.020397,0.003066,0.037829,1.854607,0.001413,1.018117,0.501448
4,(almonds),(chocolate),0.020397,0.163845,0.005999,0.294118,1.795099,0.002657,1.184553,0.452150
...,...,...,...,...,...,...,...,...,...,...
5123,"(milk, tomatoes)","(mineral water, spaghetti)",0.013998,0.059725,0.003333,0.238095,3.986501,0.002497,1.234110,0.759789
5124,(mineral water),"(spaghetti, milk, tomatoes)",0.238368,0.005866,0.003333,0.013982,2.383631,0.001935,1.008231,0.762142
5125,(spaghetti),"(mineral water, milk, tomatoes)",0.174110,0.006532,0.003333,0.019142,2.930353,0.002196,1.012856,0.797617
5126,(milk),"(mineral water, spaghetti, tomatoes)",0.129583,0.009332,0.003333,0.025720,2.756099,0.002124,1.016821,0.732026
5127,(tomatoes),"(mineral water, spaghetti, milk)",0.068391,0.015731,0.003333,0.048733,3.097846,0.002257,1.034692,0.726909